name: M3U generator

on:
  schedule:
    - cron: '0 0/3 * * *'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Instalar yt-dlp
        run: |
          sudo apt-get update
          sudo apt-get install -y yt-dlp

      - name: Configuração do Git
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

      - name: Executar script principal (com cookies seguros)
        env:
          YT_COOKIES: ${{ secrets.YOUTUBE_COOKIES }}
        run: |
          pwd
          chmod +x autorun.sh
          # Executa o script e força yt-dlp a usar os cookies da memória
          COOKIE_CMD="--cookies <(printf \"%s\" \"$YT_COOKIES\")"
          export COOKIE_CMD
          ./autorun.sh

      - name: Adicionar ficheiros ao Git
        run: |
          git add -A
          ls -la

      - name: Commit e Push
        run: |
          git commit -m "links are updated" || echo "Sem alterações para commitar"
          git push -f
